### PR TITLE
[Fixes #259] Test to verify correct project details on dashboard

### LINKED ISSUE #259: Unit Tests for Project Details
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

Write unit tests to verify the correct rendering of the project details (name, lang, description, output file name, etc.) onto the Project Table.

### Possible Solution

Render the Project Table and test the functionality using mock functions and mock projects (sent from the backend API).

### PR DESCRIPTION
**Pull request by McTechie**
# Pull Request

## What does this PR do?
Fixes #259

- Implements unit tests for the ProjectTable.js component.
- The project details including the project name, language used, library used, task, description and output file name, rendered on the Dashboard (Project Table), by the data sent from the Backend API is verified (as visible to the user).
- Mock functions and mock projects have been created to isolate the testing only to the Frontend / React-side of the app (not making any axios requests to the Backend).

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Review by rajraj889 — CHANGES_REQUESTED** [review]
Hey mcvean, nice work on the test cases.
I feel like we should combine all the test cases for project details like such,
image

**Comment by McTechie** [comment]
Thank you @rajraj889 😄
As for the tests I thought that maybe isolating every render onto the project table would be good, so as to find error if it occurs in one of the details, but the implementation you have suggested would work fine as well 😃
I'll work on the changes right away!

**Comment by McTechie** [comment]
@rajraj889 I have made the suggested changes, kindly have a look :D

**Review by rajraj889 — APPROVED** [review]
Nice work, I hope you add more test cases regarding CRUD of the whole project.

**Review by ADI10HERO — APPROVED** [review]

**Pull request merged**
