### PR TITLE
chore: Purged Unwanted Imports in BackEndApp

### LINKED ISSUE #320: Purge Unwanted Imports in BackEndApp
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

Many files present in the `BackEndApp` consist of many unused / unwanted imports.

### Possible Solution

Remove the non-essential imports from the `BackEndApp`.
This will help the codebase remain clean and concise! 😄

### PR DESCRIPTION
**Pull request by a-sambhab**
# Pull Request

## What does this PR do?
Removed the non-essential imports from the BackEndApp
Fixes #320 

 Removed all the non-essential imports from the BackEndApp to make sure that the code is clean and concise 

 <-- -If we didn't approve off or discuss your PR in Github issues or slack there's a high chance it will not be merged.

The following links the related issue to the PR (https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
-->

## What part does this affect?
- [x] BackEnd.

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Comment by a-sambhab** [comment]
@McTechie please review this PR for issue #320

**Review by McTechie — APPROVED** [review]
Looks good to me! :smile:

**Comment by McTechie** [comment]
Finally b4 merging the PR, you could change the PR title (using the conventional commits specification).

P.s. Something like `chore: purged unwanted imports in BackEndApp` would be awesome! 😉

**Review by bamblebam — APPROVED** [review]
LGTM

**Comment by a-sambhab** [comment]
Hey, can you please tell me about the further proceedings?? im new to contributing to auto-dl

**Comment by McTechie** [comment]
Ahh @a-sambhab firstly, thanks for contributing to AutoDL! ✨

As for this PR, it'll be merged asap (one review remains) so nothing else would be required to do (unless any changes are suggested xD).

You could definitely browse for more issues and tackle them as well. 😄

**Comment by a-sambhab** [comment]
Great, Thank you for being patient 😊

**Review by ADI10HERO — APPROVED** [review]
LGTM too

**Pull request merged**
