### PR TITLE
Fixes #357 issue

### LINKED ISSUE #357: Add release drafter
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

NO

### Feature Description

Release drafter to release on every new feat

### Possible Solution

Probot!

### Additional context

https://probot.github.io/apps/release-drafter/

### PR DESCRIPTION
**Pull request by Aniket-508**
# Pull Request

## What does this PR do?
Fixes #<357>
Added Release Tracker

## What part does this affect?
- [ ] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [x] Other. (Please specify below)

The pull request consists of two config files in .github/workflow folder and one file inside /github folder. It used Github Action 'Release Drafter' for drafting release notes and also makes required changes in the changelog.md file along with tracking of version numbers. More labels can be added for improved functionality.

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [ ] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Comment by bamblebam** [comment]
Please make the PR name more descriptive and concise. One should be able to tell what a PR does by looking at it.  
Also it should be Fixes #357 instead of Fixes <#357>. This one won't work.

**Comment by McTechie** [comment]
Hey @Aniket-508, Thanks for contributing! 😄

A few changes which you could try to incorporate:
- Renaming the PR title to follow the [Conventional Commits Specification](https://github.com/Auto-DL/Auto-DL/blob/main/CONTRIBUTING.md) would be great!
For example, `feat: Add Release Drafter`.
- As suggested by @bamblebam, you could link the Issue by changing `Fixes #<357>` in the PR description to `Fixes #357`.
- You could add a few more details to the PR description so as to convey what this PR (Release Drafter in particular) does.

**Review by RusherRG — CHANGES_REQUESTED** [review]
Make sure to add a new line at EOF.

**Comment by ADI10HERO** [comment]
Hey @Aniket-508, are you still working on this? Do you need any help?

**Pull request closed without merging**
