### PR TITLE
[Fixes #242] Conditional Clone Project

### LINKED ISSUE #242: Clone project only if a checkbox is selected
## Feature Request
Allow a project to be cloned only if a checkbox (Preprocessing params / Model Layers / Hyperparams) is ticked.

### Feature Description
At least one option (checkboxes given in the clone project modal) must be chosen, in order to proceed with successfully cloning any desired project.

Clone Project Modal

### PR DESCRIPTION
**Pull request by McTechie**
# Pull Request

## What does this PR do?
Fixes #242

- A Project will only be cloned if a checkbox in the Clone Project Modal (Preprocessing params / Model Layers / Hyperparams) is selected.
- If no new details are entered by the user in Step 1 of the Clone Project Modal for the new project to be cloned, the previously existing values of the project will be used.
- Fixed `useState` bug in Step2.js

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Review by ADI10HERO — APPROVED** [review]
Really like how you used conventional commits and made full use of PR template :)

**Comment by McTechie** [comment]
@ADI10HERO Thank you! 😄

**Review by rajraj889 — CHANGES_REQUESTED** [review]
image

While cloning, when going back to Clone Project - Step 1 from  Clone Project - Step 2 it adds clone again and again every time I do it.

**Comment by McTechie** [comment]
Yes, I'll work on improving this

**Pull request merged**
