### PR TITLE
[Fixes #271] feat: add ci for react

### LINKED ISSUE #271: CI - Github Actions for frontend
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?
All test related issues

### Feature Description
A ci using Github actions for building react app and running all tests

### PR DESCRIPTION
**Pull request by ADI10HERO**
# Pull Request

## What does this PR do?
Fixes #271

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [X] Other. (Please specify below)

CI Workflows.

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

Signed-off-by: Aditya Srivastava <adityasrivastava301199@gmail.com>

### CODE REVIEW

**Review by RusherRG — COMMENTED** [review]
@ADI10HERO looks good to me. The caching part is pretty nice although it seems like recently caching was added to `actions/setup-node@v2` itself so should we use that? [Reference](https://github.com/actions/setup-node#caching-packages-dependencies)

**Comment by ADI10HERO** [comment]
> @ADI10HERO looks good to me. The caching part is pretty nice although it seems like recently caching was added to `actions/setup-node@v2` itself so should we use that? [Reference](https://github.com/actions/setup-node#caching-packages-dependencies)

Oh wow, I did not know that it doesn't make sense to cache twice, though does it depend on package-lock or package.json?

**Comment by RusherRG** [comment]
> > @ADI10HERO looks good to me. The caching part is pretty nice although it seems like recently caching was added to `actions/setup-node@v2` itself so should we use that? [Reference](https://github.com/actions/setup-node#caching-packages-dependencies)
> 
> Oh wow, I did not know that. And yeah, it doesn't make sense to cache twice, though does it depend on package-lock or package.json?

It's not about caching twice, it's an optional parameter but since it's already present in `actions/setup-node@v2` why not use that it's probably better. Looks like they have just implemented whatever you did using `actions/cache` in their workflow. https://github.com/actions/setup-node/pull/272

**Comment by RusherRG** [comment]
Interesting fact: This PR number and the `actions/setup-node` PR number is the same #272 :exploding_head:

**Comment by ADI10HERO** [comment]
> It's not about caching twice, it's an optional parameter but since it's already present in `actions/setup-node@v2` why not use that it's probably better. Looks like they have just implemented whatever you did using `actions/cache` in their workflow. [actions/setup-node#272](https://github.com/actions/setup-node/pull/272)

@RusherRG Haha yeah I got that, so edited the comment but I guess it wasn't reflected on your end.
Anyway, the CI fails when I cache that way because it looks for `package-lock.json` in root dir, even thought default it changed :(

**Review by RusherRG — APPROVED** [review]

**Pull request merged**
