### PR TITLE
[Fixes #276] Logging configuration fix for local dev environment

### LINKED ISSUE #276: Fix Backend Logging Configuration
## Bug Report

The `requirements.txt` present in the `BackEndApp` contains the wrong package used for logging. The `logging.py` file utilizes the `colorlog` package for the logging of the information.

### Current Behavior

The App breaks due to the following error:

### Expected behavior/code

The logging configuration should work on a local environment without having to alter / comment out the configuration.

### ⚙️ Environment

- `Python` version(s): 3.9.6
- `OS`: Windows 10

### PR DESCRIPTION
**Pull request by McTechie**
# Pull Request

## What does this PR do?

Fixes #276 

- Altered `requirements.txt` to include the correct python logging package - `colorlog`.
- Created an empty `logs/app.log` in the `BackEndApp` directory to facilitate logging in the correct path.

## What part does this affect?
- [ ] FrontEnd.
- [x] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

The PR fixes the backend logging configuration setup using `colorlog`.

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Comment by ADI10HERO** [comment]
Can you remove the `app.log` file... 

`git commit --amend` :P 

Also that file was in .gitignore, how did it get added? 🤔

**Comment by McTechie** [comment]
Ahh @ADI10HERO  the `app.log` is an empty file... once its put in the local environment the logs will start filling it up. I could not find a way to simply add the `logs` directory without actually adding at least an empty file within it....

However, if I do remove the `logs` directory completely, the logging does not work in the local dev environment correctly, and the app breaks as well (backend server does not run).

Also I've added the `app.log` file by forcing it since it was in the .gitignore as you mentioned 😅. Should I proceed with removing the `logs` directory completely?

**Comment by ADI10HERO** [comment]
Right, so @McTechie the thing is... 
1. If you want to add an empty dir, use `.gitkeep` (an empty file that adds the dir structure)
2. I had updated the instructions in README.md to create an empty logs dir before starting the server so technically it is handled 🤔

**Comment by ADI10HERO** [comment]
Also, my only concern is if the `app.log` is being tracked then someone might add and push it accidentally. Not sure if that happens when you force add but would like to stay on a safer side.

**Comment by McTechie** [comment]
Yes @ADI10HERO I had not checked the updated README.md 😅.... I've removed the `logs` directory altogether (`git commit --amend`) :P
Also, thank you for the note on `.gitkeep` 😄

**Review by ADI10HERO — APPROVED** [review]
Although there exists a package named "colorlogs" too, so this may or may not be a fix.
But merging this as this is making more sense right now

**Pull request merged**
