### PR TITLE
feat: addition of prettierrc

### LINKED ISSUE #426: Addition of prettierrc
### Feature Description

I also found some people facing issues with `npx prettier -write` Even I faced the same thing, it's because some OS/IDE's might be using different prettier default settings. Instead of manually changing things in notepad or including overwritten changes to that file, we can have a `.prettierrc` config file for the prettier under `src/`. so everyone who does  `npx prettier --write` would get the changes which they made.

image

### PR DESCRIPTION
**Pull request by rushic24**
# Pull Request

## What does this PR do?
Fixes #426 

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [x] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Comment by RusherRG** [comment]
> @RusherRG There is no `.eslintrc` in v1-react, should I copy it there too?
> 
> Also, I referred to this https://khalilstemmler.com/blogs/tooling/prettier/ for the eslint and prettier compatibility, Let me know if it can be customized more

No need to add `.eslintrc` in v1-react. You can use the following or generate one at https://michelelarson.com/prettier-config/

```json
{
    "printWidth":120,
    "tabWidth":2,
    "useTabs":false,
    "semi":false,
    "singleQuote":true,
    "trailingComma":"es5",
    "bracketSpacing":true,
    "proseWrap":"always"
}
```

**Comment by ADI10HERO** [comment]
@rushic24  Hey can you please undo the `remove package-lock.json` commit?

**Comment by rushic24** [comment]
@ADI10HERO then there are merge conflicts

**Comment by ADI10HERO** [comment]
> @ADI10HERO then there are merge conflicts

@rushic24 well yeah, you need to override the one in the repo by yours...
You can do that by pulling the main branch --> modifying the .gitignore (if it's in the gitignore) and adding the lock file and pushing... If it still is giving conflict then I will push the code manually..

**Comment by rushic24** [comment]
@ADI10HERO It doesn't work if I just copy and paste package-lock from master. The workflow fails telling to do npm install before pushing. 

npm install updates that package-lock and there is conflict.

**Review by RusherRG — APPROVED** [review]

**Pull request merged**
