### PR TITLE
feat: add GitHub workflows for conventional checks (#335)

### LINKED ISSUE #335: GitHub workflow to run conventional lint checks
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No.

### Feature Description

Implement/use a GitHub action to run checks related to conventional commit messages and PR titles to make the messages and titles follow a certain convention defined in the [CONTRIBUTING.md](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by RusherRG**
# Pull Request

## What does this PR do?
Fixes #335 

## What part does this affect?
- [ ] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [X] Other. (GitHub workflows)

Added GitHub workflows to perform:
1. Conventional commit checks
2. PR title convention checks

## Before submitting
- [X] Was this discussed/approved via a GitHub issue or slack?
- [X] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [X] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [X] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [X] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [X] Did you make sure the code is clean and docstrings have been added or updated as required?
- [X] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [X] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Comment by RusherRG** [comment]
The PR check workflow won't work right now as mentioned [here](https://github.com/marketplace/actions/semantic-pull-request)

> This allows the action to be used in a fork-based workflow, where e.g. you want to accept pull requests in a public repository. In this case, the configuration from the main branch of your repository will be used for the check. This means that you need to have this configuration in the main branch for the action to run at all (e.g. it won't run within a PR that adds the action initially). Also if you change the configuration in a PR, the changes will not be reflected for the current PR – only subsequent ones after the changes are in the main branch.

**Comment by ADI10HERO** [comment]
> The PR check workflow won't work right now as mentioned [here](https://github.com/marketplace/actions/semantic-pull-request)
> 
> > This allows the action to be used in a fork-based workflow, where e.g. you want to accept pull requests in a public repository. In this case, the configuration from the main branch of your repository will be used for the check. This means that you need to have this configuration in the main branch for the action to run at all (e.g. it won't run within a PR that adds the action initially). Also if you change the configuration in a PR, the changes will not be reflected for the current PR – only subsequent ones after the changes are in the main branch.

This is tricky! Thanks for bringing this to our notice! 🙌

**Comment by bamblebam** [comment]
So what happens if my commits are not conventional ? Will it just fail.
And what if I have like 20 commits and some of them don't meet the guidelines ?

**Comment by bamblebam** [comment]
Also should we add this as a checkbox in the PR template ?

**Review by bamblebam — APPROVED** [review]

**Comment by RusherRG** [comment]
Yeah it fails with an output similar to the following
image

> And what if I have like 20 commits and some of them don't meet the guidelines ?

It will still fail but it does show the commits on which it failed 
image

**Comment by RusherRG** [comment]
> Also should we add this as a checkbox in the PR template ?

Maybe we can change `Did you read the contributor guidelines` to `Did you follow the contributor guidelines`

**Comment by bamblebam** [comment]
> > And what if I have like 20 commits and some of them don't meet the guidelines ?
> 
> It will still fail but it does show the commits on which it failed image

So then will I need to remove those commits, or do what exactly?

**Comment by RusherRG** [comment]
> So then will I need to remove those commits, or do what exactly?
Yes, you'll have to update the commit messages as per the conventions

**Review by ADI10HERO — APPROVED** [review]

**Pull request merged**
