### PR TITLE
Improve settings.py

### LINKED ISSUE #434: docs: Typo in the README.md
### Current Behaviour

Typo at line 40. The spelling for Hacktoberfest is wrong.

### Expected Behaviour

Fix the typo at line 40. Ch
Change ```hactoberfest``` to ```hacktoberfest```.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Additional Context

Please assign me this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by Dhruvacube**
# Pull Request

## What does this PR do?
Fixes #434 and custom issues which I found

## What part does this affect?
- [ ] FrontEnd.
- [x] BackEnd.
- [x] Documentation.
- [ ] Other. (Please specify below)

This PR fixes some security issues related with settings.py also apps was done wrongly , so it also fixes that, also applied some changes so that it is compatible with `Django 3.2`

NOTE: I am coming from `Hacktoberfest` :)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Comment by Dhruvacube** [comment]
@RusherRG its a follow up pr for #438

**Comment by Dhruvacube** [comment]
> Hey, @Dhruvacube most changes I see are unnecessary. Please create an issue first and discuss before making the PR.

ig its necessary also its followup request for the #438 so reviewer was there, also read the django docs security are important

**Comment by Dhruvacube** [comment]
@ADI10HERO do ping me if it is okay to format with black , then I will update the pr accordingly :)

**Comment by Dhruvacube** [comment]
if formatting with `blavk` is not feasible then could you please how should I revert those changes?

**Comment by ADI10HERO** [comment]
Formatting with black should be fine! 

However, I suggest you rebase the PR to the main of the repo and just make 1 change per PR! 
Both your PRs are messy and tbh, no maintainer would merge a messy PR that doesn't clearly say what it does. I am not trying to be rude here... 

If I were you, I'd have rebased this PR (close the other one) and discuss the issue on either GitHub issues or slack, propose a solution, get feedback and then make the PR. (at least when it comes to improving settings.py)

I also wouldn't have touched any file that shouldn't have been changed in that particular PR. 
For eg., Your logging PR changes some files (apparently due to linter) which have nothing to do with the changes you're proposing.

**Comment by ADI10HERO** [comment]
Also, please read [contributing guidelines](https://github.com/Auto-DL/Auto-DL/blob/41a3ffc2ec6466e68a7aa504db4a7de8c841c86d/CONTRIBUTING.md) and make appropriate changes. 

Thanks and BR!

**Comment by Dhruvacube** [comment]
> Also, please read [contributing guidelines](https://github.com/Auto-DL/Auto-DL/blob/41a3ffc2ec6466e68a7aa504db4a7de8c841c86d/CONTRIBUTING.md) and make appropriate changes.
> 
> Thanks and BR!

okay sure, just lemme get some time, then for sure, I will make the necessary changes

**Comment by ADI10HERO** [comment]
Hey closing this PR due to inactivity! (Please check out the pinned announcement)

**Pull request closed without merging**
