### PR TITLE
[Fixes #328]  Changing sizes of containers while drag and drop.

### LINKED ISSUE #328: Changing sizes of containers while drag and drop.
### Current Behavior
While dragging layers from source to target container the layer size used to change which made website a bit shaky and also while dropping layer  in delete container  there was a change in size of container.

### Expected behavior/code
while dragging dropping the container size shouldnt change  and website shouldnt be shaky .

### ⚙️ Environment

- `Python` version(s):
    - *good*: [e.g. 3.8]
    - **better**: [3.8.6 - Clang 12.0.0 (clang-1200.0.32.27)]
- `OS`: [e.g. Ubuntu 18.04, OSX 10.13.4, Windows 10]

### Possible Solution
Change the sizes of containers i.e fix correct minHeight value and  use percentage values while defining layer sizes .

### PR DESCRIPTION
**Pull request by PRA-developer-TIK**
# Pull Request

## What does this PR do?
Fixes #328 
Fixes changes in sizes of containers while drag and drop.

## What part does this affect?
- [X] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [X] Was this discussed/approved via a GitHub issue or slack?
- [X] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [X] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [X] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [X] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [X] Did you make sure the code is clean and docstrings have been added or updated as required?
- [X] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

### CODE REVIEW

**Review by rajraj889 — APPROVED** [review]
Nice :)

**Comment by ADI10HERO** [comment]
@PRA-developer-TIK  Can you please fix this conflict :)
Otherwise looks ready to be merged

**Comment by PRA-developer-TIK** [comment]
> @PRA-developer-TIK Can you please fix this conflict :)
> Otherwise looks ready to be merged

Yepp will do it

**Comment by PRA-developer-TIK** [comment]
> @PRA-developer-TIK Can you please fix this conflict :)
> Otherwise looks ready to be merged

Done

**Pull request merged**
