### PR TITLE
[Fixes #170, #215] Clean the React code 

### LINKED ISSUE #170: Cleaning of React code (All unused imports and commented lines) and remove all warnings if any
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

### LINKED ISSUE #215: App crash on logout from Step2.js screen
### Current Behavior

App crashes with the following error
image

### Expected behavior/code

Successful logout

<details>
    <summary> Complete Error Message </summary>

  ```sh

×
TypeError: Cannot read property 'lib' of null
Step2
http://localhost:3000/static/js/main.chunk.js:3942:23
  3939 | }; // console.log(components);
  3940 | 
  3941 | 
> 3942 | if (project_details.lib === new String("Pytorch").valueOf() || project_details.library === new String("Pytorch").valueOf()) {
       |                     ^  3943 |   var temp_pre_meta = {
  3944 |     dataset: {
  3945 |       name: "dataset",
View source
▼ 17 stack frames were expanded.
renderWithHooks
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:14985
mountIndeterminateComponent
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:17811
beginWork
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:19049
HTMLUnknownElement.callCallback
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:4056
beginWork$1
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:23964
performUnitOfWork
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:22776
workLoopSync
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:22707
renderRootSync
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:22670
performSyncWorkOnRoot
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:22293
scheduleUpdateOnFiber
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:21881
updateContainer
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:25482
(anonymous function)
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:26021
unbatchedUpdates
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:22431
legacyRenderSubtreeIntoContainer
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:26020
render
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/node_modules/react-dom/cjs/react-dom.development.js:26103
▲ 17 stack frames were expanded.
Module.<anonymous>
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/src/index.js:7
   4 | import App from "./App";
   5 | import reportWebVitals from "./reportWebVitals";
   6 | 
>  7 | ReactDOM.render(
   8 |   <React.StrictMode>
   9 |     <App />
  10 |   </React.StrictMode>,
View compiled
Module../src/index.js
http://localhost:3000/static/js/main.chunk.js:8348:30
__webpack_require__
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3000/static/js/main.chunk.js:8471:18
__webpack_require__
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
checkDeferredModules
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
D:/ADI/AutoDL/code/Auto-DL/FrontEndApp/v1-react/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:69


 ```

</details>

### PR DESCRIPTION
**Pull request by therajtiwari**
## Pull Request

fixes #170 and fixes #215

### Description

- Cleans all the unused imports and commented lines
- Fixes the warnings
- Fixes the app crash behavior on logout 
### Checklist:
- [x] Followed the guidelines mentioned in our [Contributing document](/CONTRIBUTING.md)
- [x] Ensured that there aren't other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change
- [x] This PR is linked to an [Issue](https://www.github.com/Auto-DL/Generator/issues) and the issue number has been mentioned in the title and body of the PR
- [x] The code is clean and docstrings have been added or updated as required
- [x] Code is linted/formatted locally prior to submission (using `prettier`)

### CODE REVIEW

**Review by ADI10HERO — CHANGES_REQUESTED** [review]
Thank you for your PR @therajtiwari 
I would recommend the following changes:
1. Remove the space between "#" and "170"
2. Use imperative mood for the PR title [(look at tip 2)](https://tighten.co/blog/building-a-great-pull-request/)
3. All the following prefix to the PR title: `[Fixes #170] ` (and a white space between "]" and "Clean"

**Comment by therajtiwari** [comment]
Thanks for the suggestions @ADI10HERO 
I have made the required changes. Please review the same.

**Comment by ADI10HERO** [comment]
> Thanks for the suggestions @ADI10HERO
> I have made the required changes. Please review the same.

Yep they look good now :)

**Review by ADI10HERO — APPROVED** [review]

**Comment by ADI10HERO** [comment]
We'll wait for @rajraj889 to complete his review and then we can merge :)

**Comment by rajraj889** [comment]
The app breaks due to the changes made in Step2.js, please look into it

**Comment by therajtiwari** [comment]
Thanks for pointing it out. I have fixed it now, please check the same.

**Comment by ADI10HERO** [comment]
Hey @therajtiwari, due to changes in the current code base, can you please merge `v1-beta` in your branch and push the new updates, that would solve the conflict (I think)

**Comment by therajtiwari** [comment]
> Hey @therajtiwari, due to changes in the current code base, can you please merge `v1-beta` in your branch and push the new updates, that would solve the conflict (I think)

Did it as well as fixed some other warnings and the logout bug. Please check the same.

**Pull request merged**
