### PR TITLE
feat: material-ui package upgrade to v5 (#409)

### PR DESCRIPTION
**Pull request by Kathuria**
# Pull Request

## What does this PR do?
Package Version Upgrade #409

 Updated version as per https://mui.com/guides/migration-v4/#theme 

Added:
   "@emotion/react": "^11.5.0",
    "@emotion/styled": "^11.3.0",
    "@mui/icons-material": "^5.0.5",
    "@mui/lab": "^5.0.0-alpha.53",
    "@mui/material": "^5.0.6",
    "@mui/styles": "^5.0.2",

Removed:
    "@material-ui/core": "^4.12.3",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.60",

Notes:
1) Error: Cannot find module '@mui/styles/makeStyles' - installed -- So need to add @mui/styles
2) /pages/_app.tsx
13:3  Error: Definition for rule '@typescript-eslint/no-empty-interface' was not found.  @typescript-eslint/no-empty-interface
-- According to https://palantir.github.io/tslint/rules/no-use-before-declare/ page, this rule is discouraged as modern TypeScript does not use it and is slow to compute. So removed this rule and validated lint.

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

Package.json and material ui-imports in various files

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Comment by Kathuria** [comment]
Screenshot 2021-10-30 at 1 41 23 PM

**Comment by Kathuria** [comment]
@RusherRG , @McTechie : Can you please review this PR and merge if looks good. In case you planned to merge later can you please add hacktoberfest-accepted label to this PR considering last day of hacktoberfest.

**Review by McTechie — CHANGES_REQUESTED** [review]
Good work on the upgrade! There are a few changes which need to be incorporated -

1. The Sidebar shown below remains open at every instant throughout the app. It should only open when the User hovers over it. Upon no activity, it should remain collapsed.
image

2. The `adaptV4Theme()` appears to be deprecated....?
image

Everything else looks good to me ✨

**Comment by Kathuria** [comment]
> Good work on the upgrade! There are a few changes which need to be incorporated -
> 
> 1. The Sidebar shown below remains open at every instant throughout the app. It should only open when the User hovers over it. Upon no activity, it should remain collapsed.
>    image
> 2. The `adaptV4Theme()` appears to be deprecated....?
>    image
> 
> Everything else looks good to me ✨

@McTechie : 

> 1. Can you share steps how can check app after login, need backend setup details - consider me new to Django application (I installed requirement and tried to run but something might be missing).

>2. Will check this as well.

**Comment by McTechie** [comment]
@Kathuria Do give [this setup video](https://youtu.be/z1mYiZ6CWok) a look, and in case you still face any problems, do let us know xD

**Pull request merged**
