### PR TITLE
test: Add unit tests for EmailTemplates class in authv1 app

### LINKED ISSUE #294: Unit Tests for EmailTemplates Class
### Feature Description
Unit test using Pytest for the class

### PR DESCRIPTION
**Pull request by Shivangik01**
# Pull Request

## What does this PR do?
Fixes #294 

Added unit tests for EmailTemplates class methods in test_email_templates.py and the utils_tests.py contains the User class instances used for testing purposes.

## What part does this affect?
- [ ] FrontEnd.
- [x] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

### CODE REVIEW

**Review by bamblebam — COMMENTED** [review]
Do we need both these files?  Because their content is the same.

**Comment by Shivangik01** [comment]
No, test_emails.py was the name of the file before the second commit, I then changed it to test_email_templates.py so that the file name includes the class name I'm testing.  So there's only 1 file which was added and changed.

**Comment by bamblebam** [comment]
> No, test_emails.py was the name of the file before the second commit, I then changed it to test_email_templates.py so that the file name includes the class name I'm testing. So there's only 1 file which was added and changed.

The PR shows that 2 files have been changed. Can you delete the old one.

**Comment by Shivangik01** [comment]
> The PR shows that 2 files have been changed. Can you delete the old one.

I'm not sure why is it showing like that, but there is only 1 file. Only the file name was changed maybe that's why it is showing 2 different files.

**Comment by bamblebam** [comment]
> I'm not sure why is it showing like that, but there is only 1 file. Only the file name was changed maybe that's why it is showing 2 different files.

@ADI10HERO can you take a look at this

**Comment by ADI10HERO** [comment]
> > I'm not sure why is it showing like that, but there is only 1 file. Only the file name was changed maybe that's why it is showing 2 different files.
> 
> @ADI10HERO can you take a look at this

Yeah sure :)

**Review by ADI10HERO — APPROVED** [review]

**Pull request merged**
