### PR TITLE
[Fixes #284] Model Layers Validation

### LINKED ISSUE #284: Model Layers Validation
### Feature Description
This feature eases the user for the choice of correct layers to be added thus creating an accurate model ,
prompting the user with a warning icon on layer itself,
suggesting user correct layer to be added with a right tick icon ,
runs a check for every render thus validating  layer tab for each layer thus added ,deleted or dragged within layer tab .

### PR DESCRIPTION
**Pull request by PRA-developer-TIK**
# Pull Request

## What does this PR do?
Fixes #284 
This PR feature validates the layers by suggesting the correct layers to be added and prompting with a warning if an invalid layer is being added by the user .The layers are validated  on every render.

## What part does this affect?
- [X] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [X] Was this discussed/approved via a GitHub issue or slack?
- [X] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [X] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [X] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [X] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [X] Did you make sure the code is clean and docstrings have been added or updated as required?
- [X] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

### CODE REVIEW

**Review by rajraj889 — CHANGES_REQUESTED** [review]
This error occurs when i try to rearrange after selecting a layer

image

**Review by rajraj889 — APPROVED** [review]
Why does the validation.js has alot of comments?

**Comment by PRA-developer-TIK** [comment]
> Why does the validation.js has alot of comments?
Actually while implementing i commented  that and also thought that it wasn't used currently but it might be used later ,so i kept it commented .

**Comment by PRA-developer-TIK** [comment]
> This error occurs when i try to rearrange after selecting a layer
> 
> image

also I fixed this error in the current PR only  !

**Review by ADI10HERO — APPROVED** [review]

**Pull request merged**
