### PR TITLE
[Fixes #145, #238] Add docker support

### LINKED ISSUE #145: Docker File and Docker Compose file
## Feature Request

Containerisation of the platform. 

### Feature Description

- Separate Docker files of front-end and back-end to be added.
- Along with the Docker file, Docker Compose file to be added.

### LINKED ISSUE #238: Use .env for CORS config
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

No

### Feature Description

There is a need for `CORS_ORIGIN` and `BACKEND_URL` in both the frontend and backend apps. So it would be better to have a `.env` to configure these variables so making it easier to run on independent servers.

### Possible Solution

Add environment variables support for `CORS_ORIGIN_WHITELIST` in `settings.py` and introduce `REACT_APP_BACKEND_API_URL` for requests from frontend to backend

### PR DESCRIPTION
**Pull request by RusherRG**
## Pull Request

fixes #145 & fixes #238

### Description

Dockerfile for both BackEndApp and FrontEndApp are added along with a docker-compose.yml for easy startup/build.

### Checklist:
- [X] Followed the guidelines mentioned in our [Contributing document](../CONTRIBUTING.md)
- [X] Ensured that there aren't other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change
- [X] This PR is linked to an [Issue](https://www.github.com/Auto-DL/Generator/issues) and the issue number has been mentioned in the title and body of the PR
- [X] The code is clean and docstrings have been added or updated as required
- [X] Code is linted/formatted locally prior to submission (using `black`)

### CODE REVIEW

**Comment by RusherRG** [comment]
It's still a work in progress. It would be great if someone could test it out.

**Review by Rahul524 — CHANGES_REQUESTED** [review]
@RusherRG 
Change the container port in the docker-compose.yml file and along with that add configuration details to the documentation.

**Comment by RusherRG** [comment]
> @RusherRG
> Change the container port in the docker-compose.yml file and along with that add configuration details to the documentation.

@Rahul524 made the necessary changes. :v:

**Comment by ADI10HERO** [comment]
Are we closing this PR? @RusherRG

**Comment by Rahul524** [comment]
> > @RusherRG
> > Change the container port in the docker-compose.yml file and along with that add configuration details to the documentation.
> 
> @Rahul524 made the necessary changes. ✌️

Will review it again.

**Comment by ADI10HERO** [comment]
Tested this on a new instance, works flawlessly!
Thanks a lot @RusherRG

**Review by ADI10HERO — APPROVED** [review]

**Pull request merged**
